version = 1

[[analyzers]]
name = "typescript"
enabled = true

  [analyzers.meta]
  # Runtime/environment must be an array
  runtime = ["nodejs"]
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true
